version: "3.8"
services:
  web:
    build: .
    ports:
      - 1337:1337
      - 8080:8080
    volumes:
      - .:/usr/local/app
  db:
    image: postgres:13.0
    environment: 
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data