apiVersion: apps/v1
kind: Deployment
metadata:
  name: sails
  labels:
    app: sails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sails
  template:
    metadata:
      labels:
        app: sails
    spec:
      containers:
      - name: sails
        image: cblair/sails:$IMAGE_VERSION
        imagePullPolicy: Always
        ports:
          - containerPort: 1337
        env:
          - name: NODE_ENV
            value: "production"
        command: ["npm", "run", "start"]